/**
 * SVG Extractor - Extract SVG data from Onshape FeatureScript custom features
 *
 * This tool extracts SVG data that was generated by the faceToSVG FeatureScript
 * and saves it to a local file.
 */

import fs from 'fs';
import path from 'path';
import { createOnshapeClient } from './onshape-api';
import { OnshapeDocumentId } from './types/onshape';

interface FeatureData {
  featureId: string;
  featureType: string;
  name: string;
  parameters?: any;
}

interface SVGExtractionOptions {
  documentId: string;
  workspaceId?: string;
  versionId?: string;
  elementId: string;
  featureId?: string; // Optional - will find faceToSVG features if not specified
  outputPath?: string; // Optional - where to save the SVG
}

export class SVGExtractor {
  private client;

  constructor(accessKey: string, secretKey: string) {
    this.client = createOnshapeClient(accessKey, secretKey);
  }

  /**
   * Extract SVG from a FeatureScript feature
   */
  async extractSVG(options: SVGExtractionOptions): Promise<string> {
    const docId: OnshapeDocumentId = {
      documentId: options.documentId,
      workspaceId: options.workspaceId,
      versionId: options.versionId,
      elementId: options.elementId
    };

    // If no feature ID specified, find all faceToSVG features
    if (!options.featureId) {
      console.log('Searching for faceToSVG features...');
      const features = await this.findFaceToSVGFeatures(docId);

      if (features.length === 0) {
        throw new Error('No faceToSVG features found in the document');
      }

      console.log(`Found ${features.length} faceToSVG feature(s)`);

      // Use the first one (or let user choose)
      options.featureId = features[0].featureId;
      console.log(`Using feature: ${features[0].name || options.featureId}`);
    }

    // Get the feature's computed parameters (where SVG is stored)
    const svgData = await this.getFeatureSVG(docId, options.featureId);

    // Save to file if output path specified
    if (options.outputPath) {
      this.saveSVG(svgData, options.outputPath);
      console.log(`SVG saved to: ${options.outputPath}`);
    }

    return svgData;
  }

  /**
   * Find all faceToSVG features in a part studio
   */
  async findFaceToSVGFeatures(docId: OnshapeDocumentId): Promise<FeatureData[]> {
    // TODO: Implement API call to get features list
    // Endpoint: GET /api/partstudios/d/:did/[wvm]/:wvm/e/:eid/features
    throw new Error('Not implemented: findFaceToSVGFeatures - needs API implementation');
  }

  /**
   * Get SVG data from a specific feature
   */
  async getFeatureSVG(docId: OnshapeDocumentId, featureId: string): Promise<string> {
    // TODO: Implement API call to get feature's computed parameters
    // The SVG is stored in the feature's "svgOutput" computed parameter
    // Endpoint: GET /api/partstudios/d/:did/[wvm]/:wvm/e/:eid/features/featureid/:fid
    throw new Error('Not implemented: getFeatureSVG - needs API implementation');
  }

  /**
   * Save SVG to file
   */
  saveSVG(svgData: string, outputPath: string): void {
    const dir = path.dirname(outputPath);

    // Create directory if it doesn't exist
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    // Write SVG file
    fs.writeFileSync(outputPath, svgData, 'utf-8');
  }

  /**
   * Extract SVG from URL
   */
  static async extractFromUrl(
    url: string,
    accessKey: string,
    secretKey: string,
    outputPath?: string
  ): Promise<string> {
    const docId = createOnshapeClient(accessKey, secretKey).constructor.parseDocumentUrl(url);

    if (!docId) {
      throw new Error('Invalid Onshape URL');
    }

    const extractor = new SVGExtractor(accessKey, secretKey);

    return await extractor.extractSVG({
      documentId: docId.documentId,
      workspaceId: docId.workspaceId,
      versionId: docId.versionId,
      elementId: docId.elementId,
      outputPath
    });
  }
}

/**
 * CLI function to extract SVG
 */
export async function extractSVGCLI() {
  const accessKey = process.env.ONSHAPE_ACCESS_KEY;
  const secretKey = process.env.ONSHAPE_SECRET_KEY;

  if (!accessKey || !secretKey) {
    console.error('Error: Onshape API credentials not set');
    console.error('Set ONSHAPE_ACCESS_KEY and ONSHAPE_SECRET_KEY environment variables');
    process.exit(1);
  }

  // Get document URL from command line
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.log('Usage: npm run extract-svg <onshape-url> [output-file]');
    console.log('');
    console.log('Example:');
    console.log('  npm run extract-svg "https://cad.onshape.com/documents/abc.../w/def.../e/ghi..." output.svg');
    process.exit(1);
  }

  const url = args[0];
  const outputPath = args[1] || 'output.svg';

  try {
    console.log('Extracting SVG from Onshape...');
    console.log(`URL: ${url}`);

    const svg = await SVGExtractor.extractFromUrl(url, accessKey, secretKey, outputPath);

    console.log('Success!');
    console.log(`SVG length: ${svg.length} characters`);
  } catch (error) {
    console.error('Error:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  extractSVGCLI();
}
